---
# tasks file for miniconda role

- name: Download miniconda python distribution
  sudo: False
  get_url:
    url: "{{ url }}"
    dest: /tmp/miniconda.sh
    mode: 0755

- name: Add conda group
  sudo: True
- group:
    name: conda
    state: present

- name: Add anaconda account
  sudo: True
  user: name={{ item }}
        group=users
        groups=conda
        shell=/bin/bash
        append=yes
        state=present
        createhome=yes
  with_items:
    - conda

- name: Execute the miniconda setup script
  sudo: True
  shell: /tmp/miniconda.sh -b -p {{ miniconda_home }} creates={{ miniconda_home }} executable=/bin/bash
  notify:
    - remove miniconda setup script

- name: Set dir permissions
  sudo: True
  file: dest={{ miniconda_home }}
        state=directory
        owner=root
        group=users
        mode='u=rwX,g=rwX,o=rX'
        recurse=yes

- name: Add miniconda to the PATH
  sudo: True
  shell: "echo '{{ item }}' >> /etc/profiles.d executable=/bin/bash"
  with_items:
  - "export PATH={{ miniconda_home }}/bin:$PATH"

- name: Update conda to latest version
  sudo: False
  shell: "{{ miniconda_home }}/bin/conda update conda --yes -q executable=/bin/bash"

- name: Install pip
  sudo: False
  shell: "{{ miniconda_home }}/bin/conda install pip --yes -q executable=/bin/bash"
