---
# tasks file for miniconda role

- name: Download miniconda python distribution
  sudo: False
  get_url:
    url: "{{ url }}"
    dest: /tmp/miniconda.sh
    mode: 0755

- name: Execute the miniconda setup script
  sudo: True
  shell: /tmp/miniconda.sh -b -p {{ miniconda_home }} creates={{ miniconda_home }} executable=/bin/bash
  notify:
    - remove miniconda setup script

- name: Add miniconda to the PATH
  sudo: True
  shell: "echo '{{ item }}' >> /etc/profiles.d executable=/bin/bash"
  with_items:
  - "export PATH={{ miniconda_home }}/bin:$PATH"

- name: Update conda to latest version
  sudo: False
  shell: "{{ miniconda_home }}/bin/conda update conda --yes -q executable=/bin/bash"

- name: Install pip
  sudo: False
  shell: "{{ miniconda_home }}/bin/conda install pip --yes -q executable=/bin/bash"
